name: Update Root Repository on Submodule Change

on:
  repository_dispatch:
    types: [update_submodule]

jobs:
  update-root:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Root Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Check Submodule Status
        run: git submodule status

      - name: Debug GitHub Secrets
        run: |
          if [ -z "${{ secrets.GH_PAGES_PAT }}" ]; then
            echo "❌ GH_PAGES_PAT is not set!"
            exit 1
          else
            echo "✅ GH_PAGES_PAT is set."
          fi

      - name: Ensure Correct Git Authentication
        run: |
          git config --global user.name "Iol-lshh"
          git config --global user.email "markhong93@naver.com"
          git remote remove origin || true
          git remote add origin https://x-access-token:${{ secrets.GH_PAGES_PAT }}@github.com/Iol-lshh/Iol-lshh.github.io.git
          git remote -v

      - name: Initialize and Update Submodules
        run: |
          git submodule init
          git submodule update --remote --recursive

      - name: Update Submodule Reference
        run: |
          git submodule update --remote --merge
          git add content/blog
          git diff --cached --exit-code || git commit -m "chore: update submodule reference"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
    
      - name: Install dependencies
        run: |
            npm ci    

      - name: Build Deploy
        env:
          GA_PROPERTY_ID: ${{ secrets.GA_PROPERTY_ID }}
        run: |
          echo "Deploying with Gatsby..."
          npx gatsby build --prefix-paths
          npx gh-pages -d public --repo "https://x-access-token:${{ secrets.GH_PAGES_PAT }}@github.com/iol-lshh/Iol-lshh.github.io.git"
    