name: Update Root Repository on Submodule Change

on:
  repository_dispatch:
    types: [update_submodule]

jobs:
  update-root:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Root Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Check Submodule Status
        run: git submodule status

      - name: Configure Git Authentication
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAGES_PAT }}@github.com/Iol-lshh/Iol-lshh.github.io.git

      - name: Initialize and Update Submodules
        run: |
          git submodule init
          git submodule update --remote --recursive

      - name: Update Submodule Reference
        run: |
          git submodule update --remote --merge
          git add content/blog
          git commit -m "chore: update submodule reference" || echo "No changes to commit"

      - name: Push Changes to Root Repository
        run: |
          git push origin main || echo "No changes to push"
